USE [master]
GO

/****** Object:  Database [Car_DWH]    Script Date: 3/27/2024 8:52:54 PM ******/
CREATE DATABASE [Car_DWs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Car_DWs', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Car_DWs.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Car_DWs_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Car_DWs_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Car_DWs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Car_DWs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Car_DWs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Car_DWs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Car_DWs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Car_DWs] SET ARITHABORT OFF 
GO

ALTER DATABASE [Car_DWs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Car_DWs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Car_DWs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Car_DWs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Car_DWs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Car_DWs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Car_DWs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Car_DWs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Car_DWs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Car_DWs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Car_DWs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Car_DWs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Car_DWs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Car_DWs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Car_DWs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Car_DWs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Car_DWs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Car_DWs] SET RECOVERY FULL 
GO

ALTER DATABASE [Car_DWs] SET  MULTI_USER 
GO

ALTER DATABASE [Car_DWs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Car_DWs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Car_DWs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Car_DWs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Car_DWs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Car_DWs] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Car_DWs] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Car_DWs] SET  READ_WRITE 
GO


